# Production Configuration
# This file contains production-specific settings

environment: production
debug: false

database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  name: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  pool_size: 20
  max_overflow: 50

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  db: ${REDIS_DB}
  max_connections: 20

api:
  host: 0.0.0.0
  port: 8000
  debug: false
  cors_origins:
    - ${CORS_ORIGIN_1}
    - ${CORS_ORIGIN_2}
  jwt_secret: ${JWT_SECRET}
  jwt_algorithm: "HS256"
  jwt_expire_minutes: 30

llm:
  provider: "openai"
  api_key: ${LLM_API_KEY}
  model: "gpt-4o-mini"
  temperature: 0.7
  max_tokens: 4000
  timeout: 30

search:
  provider: "duckduckgo"
  brave_api_key: ${BRAVE_API_KEY}
  tavily_api_key: ${TAVILY_API_KEY}
  max_results: 10
  timeout: 10

logging:
  level: "INFO"
  debug: false
  log_file: "/var/log/project-management/app.log"
  error_file: "/var/log/project-management/error.log"
  structured_file: "/var/log/project-management/structured.log"


